inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins: 
  - rubocop-rspec

# すべての新しいCopを自動で有効にする
AllCops:
  NewCops: enable

# 中括弧の内側に半角スペースを必要とする
Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space
