default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_ROOT_USER'] %>
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: <%= ENV['MYSQL_DB'] %>_development

test:
  <<: *default
  database: <%= ENV['MYSQL_DB'] %>_test
#
production:
  <<: *default
  database: <%= ENV['MYSQL_DB'] %>_production
  username: <%= ENV['MYSQL_ROOT_USER'] %>
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
